version: "3.8"
services:
  front:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    command: sh -c 'npm run dev'
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./front:/front"
    working_dir: /front
  storybook:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    command: sh -c 'yarn storybook'
    ports:
      - "6006:6006"
    volumes:
      - "./front:/front"
    working_dir: /front
