import { NextPage, GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import { Blog, CategoryProps } from "../interfaces/index";
import { client } from "../libs/client";
import Layout from "../components/Layout/Layout";
import Posts from "../components/Posts/Posts";
import { perpage } from "../constants";

type Props = {
  blogs: Blog[];
  categories: CategoryProps[];
  totalCount: number;
};

const Home: NextPage<Props> = ({ blogs, categories, totalCount }) => {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Hayakawa&apos;s Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-1 bg-stone-100 block justify-center items-center font-Body">
        <Layout categories={categories}>
          <Posts totalCount={totalCount} blogs={blogs} />
        </Layout>
      </main>
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const blog = await client.get({ endpoint: "blog" });
  const paths = [...Array(Math.ceil(blog.totalCount / perpage))].map(
    (_, page: number) => {
      return `/${page + 1}`;
    }
  );

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const id = context.params?.id as string;
  const blog = await client.get({
    endpoint: "blog",
    queries: {
      offset: (Number(id) - 1) * perpage,
      limit: perpage,
    },
  });
  const category = await client.get({ endpoint: "category" });

  return {
    props: {
      blogs: blog.contents as Blog[],
      categories: category.contents as CategoryProps[],
      totalCount: blog.totalCount as number,
    },
  };
};

export default Home;
