import { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { client } from "../libs/client";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import Tag from "../components/Tag/Tag";
import { Blog, Category } from "../interfaces/index";
import ArticleCard from "../components/ArticleCard/ArticleCard";

type Props = { blogs: Blog[]; categories: Category[] };

const Home: NextPage<Props> = ({ blogs, categories }: Props) => {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Hayakawa&apos;s Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-1 overflow-x-hidden bg-blue-50 block items-center">
        <Header />
        <div className="mt-6 sm:mt-20 p-6 max-w-6xl container mx-auto">
          <h1 className="font-bold text-3xl sm:text-center mb-10">記事一覧</h1>
          <ul className="sm:flex sm:flex-wrap w-full sm:justify-between sm:items-start">
            {blogs.map((blog: Blog, index) => (
              <ArticleCard key={index} {...blog} />
            ))}
          </ul>
        </div>
        <div className="mt-6 sm:mt-20 p-6 max-w-6xl container mx-auto">
          <h1 className="font-bold text-3xl sm:text-center mb-10">タグ</h1>
          <ul className="sm:flex sm:flex-wrap w-full sm:justify-between sm:items-start">
            {categories.map((category: Category, index) => (
              <Tag key={index} bgColor={"bg-gray-200"} {...category} />
            ))}
          </ul>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const blog = await client.get({ endpoint: "blog" });
  const category = await client.get({ endpoint: "category" });

  return {
    props: {
      blogs: blog.contents as Blog[],
      categories: category.contents as Category[],
    },
  };
};

export default Home;
