import { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBlog } from "@fortawesome/free-solid-svg-icons";
import { Blog, CategoryProps } from "../interfaces/index";
import { client } from "../libs/client";
import ArticleCard from "../components/ArticleCard/ArticleCard";
import Layout from "../components/Layout/Layout";

type Props = { blogs: Blog[]; categories: CategoryProps[] };

const Home: NextPage<Props> = ({ blogs, categories }: Props) => {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Hayakawa&apos;s Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-1 overflow-x-hidden bg-stone-100 block justify-center items-center font-Body">
        <Layout categories={categories}>
          <div className="flex justify-center items-center mt-6 md:mt-12 mb-10">
            <FontAwesomeIcon icon={faBlog} size={"3x"} />
            <h1 className="font-bold text-3xl text-blue-800 ml-2">Tech</h1>
          </div>
          <ul className="sm:grid sm:grid-cols-2">
            {blogs.map((blog: Blog, index) => (
              <ArticleCard key={index} {...blog} />
            ))}
          </ul>
        </Layout>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const blog = await client.get({ endpoint: "blog" });
  const category = await client.get({ endpoint: "category" });

  return {
    props: {
      blogs: blog.contents as Blog[],
      categories: category.contents as CategoryProps[],
    },
  };
};

export default Home;
